---
title: "Summer Flounder Conceptual Model"
author: "Sarah Gaichas, Geret DePiper"
date: "`r format(Sys.time(), '%d %B, %Y')`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)

PKG <- c(#"foreign","foodweb","sna",
         "DiagrammeR","circlize","RColorBrewer","QPress",
         "chorddiag")

for (p in PKG) {
  if(!require(p,character.only = TRUE)) {
    install.packages(p)
    require(p,character.only = TRUE)}
}

#install QPress
#install.packages(c("tcltk2", "XML", "devtools"))
#devtools::install_github("SWotherspoon/QPress", build_vignettes = TRUE)

#install chorddiag
#devtools::install_github("mattflor/chorddiag")

```


```{r sfmod setup, message=FALSE}
#assumes this is a project and .dia file is in local directory
edges <- model.dia("Summer_Flounder_July22_2019.dia")

## Examine unweighted adjacency matrix
FLUKE <- adjacency.matrix(edges, labels=TRUE)

FLUKE_Drivers <- c("Economic Drivers","Temperature","Shifts in Preferences","Community Vulnerability","Freshwater Influx","Nutrient Influx","Ocean Acidification",
                   "Ocean Features","Oceanographic Transport","Dissolved Oxygen","Water Diversion")
FLUKE_Habitat <- c("Estuarine Habitat","Food Web Changes","Offshore Habitat","Habitat Alteration","Habitat Disturbance","Loose Inert Substrate","Salinity","Water Clarity",
                   "Aquatic Vegetation")
FLUKE_Biota <- c("Fluke Distributional Shift","Fluke Recruitment","Fluke SSB","Adults & Spawners","Age & Size Structure",
                 "Growth","Maturation","Natural Mortality","Sex Ratio")
FLUKE_Species <- c("Other Species Distributional Shifts","Protected Species")
FLUKE_Management <- c("Allocation","Communication","Enforcement","Management Control","Other Regulations",
                      "Permit Access","Regulatory Complexity","Risk Buffering")
FLUKE_Benefits <- c("Commercial Profits","Consumer Surplus","Recreational Value","Seafood","Recreational Profits")
FLUKE_Science <- c("Assessment Process","Data Quality","Predictability of Recreational Fishing","Stock Assessment")
FLUKE_Fishery <- c("Compliance","Discards","Fishery Distributional Shift","Fishery Resilience",
                   "Fleet Diversity","Landings","Perceived Inequity","Technical Interactions")

FLUKE_C <- brewer.pal(8,"Dark2")

FLUKE_Colors <- data.frame(row.names(FLUKE))
colnames(FLUKE_Colors) <- "Focus"

FLUKE_Colors$Color <- FLUKE_C[1]
FLUKE_Colors$Color[FLUKE_Colors$Focus%in%FLUKE_Habitat] <- FLUKE_C[2]
FLUKE_Colors$Color[FLUKE_Colors$Focus%in%FLUKE_Biota] <- FLUKE_C[3]
FLUKE_Colors$Color[FLUKE_Colors$Focus%in%FLUKE_Species] <- FLUKE_C[4]
FLUKE_Colors$Color[FLUKE_Colors$Focus%in%FLUKE_Management] <- FLUKE_C[5]
FLUKE_Colors$Color[FLUKE_Colors$Focus%in%FLUKE_Benefits] <- FLUKE_C[6]
FLUKE_Colors$Color[FLUKE_Colors$Focus%in%FLUKE_Science] <- FLUKE_C[7]
FLUKE_Colors$Color[FLUKE_Colors$Focus%in%FLUKE_Fishery] <- FLUKE_C[8]

FLUKE_Groups <- FLUKE_Colors
FLUKE_Groups$Group <- "Drivers"
FLUKE_Groups$Rank <- 1
FLUKE_Groups$Group[FLUKE_Groups$Focus%in%FLUKE_Habitat] <- "Habitat"
FLUKE_Groups$Rank[FLUKE_Groups$Focus%in%FLUKE_Habitat] <- 2
FLUKE_Groups$Group[FLUKE_Groups$Focus%in%FLUKE_Biota] <- "Fluke Dynamics"
FLUKE_Groups$Rank[FLUKE_Groups$Focus%in%FLUKE_Biota] <- 3
FLUKE_Groups$Group[FLUKE_Groups$Focus%in%FLUKE_Species] <- "Other Biota"
FLUKE_Groups$Rank[FLUKE_Groups$Focus%in%FLUKE_Species] <- 4
FLUKE_Groups$Group[FLUKE_Groups$Focus%in%FLUKE_Management] <- "Management"
FLUKE_Groups$Rank[FLUKE_Groups$Focus%in%FLUKE_Management] <- 5
FLUKE_Groups$Group[FLUKE_Groups$Focus%in%FLUKE_Benefits] <- "Benefits"
FLUKE_Groups$Rank[FLUKE_Groups$Focus%in%FLUKE_Benefits] <- 6
FLUKE_Groups$Group[FLUKE_Groups$Focus%in%FLUKE_Science] <- "Science"
FLUKE_Groups$Rank[FLUKE_Groups$Focus%in%FLUKE_Science] <- 7
FLUKE_Groups$Group[FLUKE_Groups$Focus%in%FLUKE_Fishery] <- "Fishing Fleets"
FLUKE_Groups$Rank[FLUKE_Groups$Focus%in%FLUKE_Fishery] <- 8

FLUKE_edges <- cbind(FLUKE,FLUKE_Colors)
FLUKE_Colors <- FLUKE_Colors[order(FLUKE_Colors$Color,FLUKE_Colors$Focus),]
FLUKE_Colors <- matrix(FLUKE_Colors$Color,dimnames=list(FLUKE_Colors$Focus,"Color"))
FLUKE_edges <-  FLUKE_edges[order( FLUKE_edges$Color,FLUKE_edges$Focus),]

FLUKE_edges$Color <- NULL
FLUKE_edges$Focus <- NULL


FLUKE_edges <- data.matrix(FLUKE_edges)
Border_mat <- matrix(1,nrow=nrow(FLUKE_edges),ncol=ncol(FLUKE_edges))
rownames(Border_mat) <- rownames(FLUKE_edges)
colnames(Border_mat) <- colnames(FLUKE_edges)
#Border_mat[Grand_Banks_edges < 0] = 2
Border_Col <- matrix("white",nrow=nrow(FLUKE_edges),ncol=ncol(FLUKE_edges))
rownames(Border_Col) <- rownames(FLUKE_edges)
colnames(Border_Col) <- colnames(FLUKE_edges)
#Border_Col[Grand_Banks_edges < 0] = "black"

Border_w <- matrix(.0001,nrow=nrow(FLUKE_edges),ncol=ncol(FLUKE_edges))
rownames(Border_w) <- rownames(FLUKE_edges)
colnames(Border_w) <- colnames(FLUKE_edges)

```

## Static Plot

```{r sfstatic}
#full conceptual model in circlize package
chordDiagram(FLUKE_edges, directional=0,
                   grid.col = FLUKE_Colors,
                   row.col = FLUKE_Colors,
                   link.lty = Border_mat,
                   link.lwd = Border_w,
                   link.border = Border_Col,
                   annotationTrack="grid",preAllocateTracks= list(track.height=0.5))

circos.trackPlotRegion(track.index=1, panel.fun= function (x,y){
  xlim = get.cell.meta.data("xlim")
  ylim = get.cell.meta.data("ylim")
  sector.name = get.cell.meta.data("sector.index")
  circos.text(mean(xlim),ylim[1],sector.name,facing="clockwise", niceFacing=TRUE, adj =c(0,0.5), cex=.6)
}, bg.border=NA) 

legend(x=-1.1,y = 1.09,legend = c("Driver","Habitat","Fluke","Other Biota","Management","Benefits","Science","Fishing Fleets"),
             lty= c(1,1,1,1,1,1,1,1), lwd=c(5,5,5,5,5,5,5,5),
             col =c(FLUKE_C[1],FLUKE_C[2],FLUKE_C[3],FLUKE_C[4],FLUKE_C[5],FLUKE_C[6],FLUKE_C[7],FLUKE_C[8]), ncol=1, cex = .75, bg = NULL, box.col=NULL, bty = "n")
title(main="Fluke System", line=-35)


```

## Interactive Plot

These are currently out of order and not getting the right colors
```{r sfint1}

chorddiag(FLUKE, 
          type = "directional",
          width = 900,
          height = 900,
          margin=150,
          groupColors = FLUKE_Colors,
          #groupedgeColor = FLUKE_Colors,
          #         link.lty = Border_mat,
          #        link.lwd = Border_w,
          #chordedgeColor = Border_Col,
          #         annotationTrack="grid",preAllocateTracks= list(track.height=0.5)
          showTicks = F, groupnameFontsize = 12, groupnamePadding = 20
          )

```

